import { SuccessPack } from "./types";

export const PRICING_CURRENCY = {
  symbol: "$",
  locale: "en-US",
};

export const BDT_PER_USD = 122;
export const YEARLY_DISCOUNT_RATE = 0.2;
export const YEARLY_DISCOUNT_MULTIPLIER = 0.8;

export const SUCCESS_PACKS: SuccessPack[] = [
  {
    id: "starter",
    nameKey: "starter",
    color: "#e06b5d",
    hours: 4,
    priceNew: 190,
    priceReturning: 223.53,
    recommendedKey: "starter",
    features: {
      projectManagement: false,
      emailPhoneSupport: true,
      trainingCoaching: true,
      configuration: true,
      dataImport: false,
      onsiteConsulting: false,
      customization: false,
      development: false,
      performanceIssues: false,
    },
  },
  {
    id: "basic",
    nameKey: "basic",
    color: "#6c757d",
    hours: 25,
    priceNew: 977.5,
    priceReturning: 1150,
    recommendedKey: "basic",
    features: {
      projectManagement: true,
      emailPhoneSupport: true,
      trainingCoaching: true,
      configuration: true,
      dataImport: true,
      onsiteConsulting: false,
      customization: true,
      development: false,
      performanceIssues: false,
    },
  },
  {
    id: "standard",
    nameKey: "standard",
    color: "#e06b5d",
    hours: 50,
    priceNew: 1904,
    priceReturning: 2240,
    recommendedKey: "standard",
    features: {
      projectManagement: true,
      emailPhoneSupport: true,
      trainingCoaching: true,
      configuration: true,
      dataImport: true,
      onsiteConsulting: true,
      customization: true,
      development: true,
      performanceIssues: true,
    },
    highlighted: true,
  },
  {
    id: "custom",
    nameKey: "custom",
    color: "#3aafa9",
    hours: 100,
    priceNew: 3400,
    priceReturning: 2500,
    recommendedKey: "custom",
    features: {
      projectManagement: true,
      emailPhoneSupport: true,
      trainingCoaching: true,
      configuration: true,
      dataImport: true,
      onsiteConsulting: true,
      customization: true,
      development: true,
      performanceIssues: true,
    },
  },
  {
    id: "pro",
    nameKey: "pro",
    color: "#3aafa9",
    hours: 200,
    priceNew: 6800,
    priceReturning: 8000,
    recommendedKey: "pro",
    features: {
      projectManagement: true,
      emailPhoneSupport: true,
      trainingCoaching: true,
      configuration: true,
      dataImport: true,
      onsiteConsulting: true,
      customization: true,
      development: true,
      performanceIssues: true,
    },
  },
];
